Repository walt-id/waltid-identity, pull requests merged in 2024-09, with the labels that each got.

#723 feat: define optional and disabled by default external signature endpoints feature
  waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/providers/OpenIDCredentialWallet.kt
  waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/providers/OpenIDProvider.kt
  waltid-services/waltid-e2e-tests/config/_features.conf
  waltid-services/waltid-e2e-tests/src/test/kotlin/E2ETest.kt
  waltid-services/waltid-e2e-tests/src/test/kotlin/ExchangeApi.kt
  waltid-services/waltid-e2e-tests/src/test/kotlin/ExchangeExternalSignaturesApi.kt
  waltid-services/waltid-e2e-tests/src/test/kotlin/LspPotentialWallet.kt
  waltid-services/waltid-wallet-api/config/_features.conf
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/FeatureCatalog.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/Main.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/WalletService.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/oidc4vc/CredentialFilterUtils.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/oidc4vc/TestCredentialWallet.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeController.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeExternalSignaturesController.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/OpenAPICommons.kt
Labels: enhancement

#689 Enhance errors handling in issuer-api
  waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/IssuanceRequests.kt
  waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/IssuerApi.kt
  waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/OnboardingRequest.kt
  waltid-services/waltid-service-commons/src/main/kotlin/id/walt/commons/web/plugins/StatusPages.kt
Labels: enhancement

#728 fix: improve displaying of error in usePresentationRequest endpoint
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt
Labels: enhancement

#729 feat: extend external signature endpoints to facilitate pre-authorized OID4VCI flow
  waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/data/ProofOfPossession.kt
  waltid-services/waltid-e2e-tests/src/test/kotlin/ExchangeExternalSignaturesApi.kt
  waltid-services/waltid-e2e-tests/src/test/kotlin/IssuerApi.kt
  waltid-services/waltid-e2e-tests/src/test/resources/issuance/universitydegree-issuance-request.json
  waltid-services/waltid-e2e-tests/src/test/resources/presentation/batch-openbadge-universitydegree-presentation-request.json
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/WalletServiceManager.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/CredentialOfferProcessor.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/IssuanceService.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/ProofOfPossessionParameterFactory.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/usecase/claim/ClaimCommons.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/usecase/claim/ExplicitClaimStrategy.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/usecase/claim/ExternalSignatureClaimStrategy.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeController.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeExternalSignaturesController.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeUtils.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/OpenAPICommons.kt
Labels: enhancement

#769 docs: fix did doc config example in did lib README.md
  waltid-libraries/waltid-did/README.md
Labels: documentation

#761 WAL-242 refactor and add sdjwt vc support in external signature handlers
  waltid-services/waltid-e2e-tests/src/test/kotlin/E2ETest.kt
  waltid-services/waltid-e2e-tests/src/test/kotlin/E2ETestWebService.kt
  waltid-services/waltid-e2e-tests/src/test/kotlin/ExchangeExternalSignaturesApi.kt
  waltid-services/waltid-e2e-tests/src/test/kotlin/IssuerApi.kt
  waltid-services/waltid-e2e-tests/src/test/kotlin/LspPotentialIssuance.kt
  waltid-services/waltid-e2e-tests/src/test/kotlin/LspPotentialWallet.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/WalletServiceManager.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/CredentialDataResult.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/IssuanceService.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/IssuanceServiceBase.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/IssuanceServiceExternalSignatures.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/ProofOfPossessionParameterFactory.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/oidc4vc/TestCredentialWallet.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/usecase/claim/ClaimCommons.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/usecase/claim/ExternalSignatureClaimStrategy.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/usecase/claim/SilentClaimStrategy.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeController.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeExternalSignaturesController.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeUtils.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/models/oid4vci/PrepareOID4VCIRequest.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/models/oid4vci/PrepareOID4VCIResponse.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/models/oid4vci/SubmitOID4VCIRequest.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/models/oid4vp/IETFSdJwtVpProofParameters.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/models/oid4vp/IETFSdJwtVpTokenProof.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/models/oid4vp/PrepareOID4VPRequest.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/models/oid4vp/PrepareOID4VPResponse.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/models/oid4vp/SubmitOID4VPRequest.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/models/oid4vp/W3cJwtVpProofParameters.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/openapi/ExchangeOpenApiCommons.kt
  waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/openapi/examples/ExchangeExternalSignaturesExamples.kt
  waltid-services/waltid-wallet-api/src/test/kotlin/id/walt/webwallet/usecase/claim/SilentClaimStrategyTest.kt
Labels: enhancement, wallet-api
